package com.company.ems.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

@Slf4j
@Service
public class ReportGeneratorService {

    private final ExecutorService executorService = Executors.newFixedThreadPool(2);

    @Scheduled(fixedRateString = "${ems.report.fixed-rate:60000}")
    public void generateMonthlyReport() {
        try {
            log.info("Starting monthly performance report generation in background...");
            
            // Explicit thread usage to avoid blocking scheduled thread
            executorService.submit(() -> {
                try {
                    log.info("Background report generation started in thread: {}", Thread.currentThread().getName());
                    
                    // Create reports directory if it doesn't exist
                    File reportsDir = new File("reports");
                    if (!reportsDir.exists()) {
                        reportsDir.mkdir();
                    }

                    // Filename with timestamp
                    String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
                    String fileName = "reports/monthly_report_" + timestamp + ".txt";
                    File reportFile = new File(fileName);

                    // Write to file
                    try (FileWriter writer = new FileWriter(reportFile)) {
                        writer.write("Employee Management System (Microservice) - Monthly Report\n");
                        writer.write("Generated at: " + LocalDateTime.now() + "\n");
                        writer.write("Status: SUCCESS\n");
                        writer.write("--------------------------------------------------\n");
                        writer.write("Report generated by background thread successfully.\n");
                    }

                    System.out.println("Monthly report generated successfully.");
                    log.info("Monthly report file created: {}", reportFile.getAbsolutePath());
                } catch (IOException e) {
                    log.error("Failed to write report file: {}", e.getMessage());
                } catch (Exception e) {
                    log.error("Error during background report generation: {}", e.getMessage());
                }
            });
            
        } catch (Exception ex) {
            log.error("Error submitting report generation task: {}", ex.getMessage(), ex);
        }
    }
}
